- name: Setting up DB
  hosts: DB
  become: yes
  vars:
   login_host: db.mkaws.online
  vars_prompt:
  - name: mysql_root_password 
    prompt: please enter mysql root password
    private: no
  tasks:
  - name: installing mysql-server
    ansible.builtin.dnf: 
     name: mysql-server
     state: latest


  - name: starting mysql
    ansible.builtin.service:
     name: mysqld
     state: restarted
     enabled: yes

 

  # check passwd is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
      filter: version  
    ignore_errors: yes 
    register: mysql_connection_output 

  - name: print output of connection of mysql
    ansible.builtin.debug:
     msg: "output: {{mysql_connection_output}}"  

  - name: setting up root passwd for mysql
    ansible.builtin.command:  "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
    when: mysql_connection_output.failed is true
